analyzer:
  skip_excluded: true

excludes:
  paths:
    - pattern: "**/.venv/**"
      reason: "TEST_TOOL_OF"
      comment: "Exclude virtualenv and jupyter labextensions to avoid unmanaged node deps without lockfiles."
    - pattern: ".venv/**"
      reason: "TEST_TOOL_OF"
      comment: "Exclude virtualenv (root-level) to avoid unmanaged node deps without lockfiles."
    - pattern: "**/node_modules/**"
      reason: "BUILD_TOOL_OF"
      comment: "Skip installed dependencies; lockfiles capture them."
    - pattern: "node_modules/**"
      reason: "BUILD_TOOL_OF"
      comment: "Skip installed dependencies; lockfiles capture them."
    - pattern: "**/.git/**"
      reason: "OTHER"
      comment: "Skip VCS metadata."
    - pattern: "**/.svn/**"
      reason: "OTHER"
      comment: "Skip VCS metadata."
    - pattern: "**/dist/**"
      reason: "BUILD_TOOL_OF"
      comment: "Skip build outputs."
    - pattern: "**/build/**"
      reason: "BUILD_TOOL_OF"
      comment: "Skip build outputs."
  scopes:
    - pattern: ".*"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Skip dependency scopes to avoid downloading third-party artifacts during scan."
